/pathfinder:
  spin_rate: 10                       # operating rate of this node

  desired_speed: 1.6

  apply_median_filter: false

  filter_size: 3

  clustering_threshold: 0.2           # constant used for cone clustering

  num_of_path_points: 5               # num of points for path visualisation

  time_interval: 0.33333                  # time interval between each path point

  max_steering: 24.0                  # in degree (positive)

  processing_range: 3.0              # in meter (drop all data outside this range)

  clearance_radius: 1.2              # in meter (collision free boundary)

  ideal_range_size: 0.3

  odom_topic: "/pose"                 # topic to receive pose

  cones_topic: "/cones"               # topic to receive cones markers

  use_laserscan: true                # enable/disable use of raw laserscan data

  laser_topic: "/scan"                # topic to receive raw laserscan

  cmdvel_topic: "/rossae/cmdvel"      # topic to publish control command

  path_topic: "/pathfinder/path"      # topic to publish path markers

  publish_cones: true                 # enable/disable cones visualisation (only valid when use_laserscan is true)

  publish_path: true                  # enable/disable path visualisation

  frame_id: "laser"                   # should be same as frame id used in laser_topic

  ranges_topic: "/pathfinder/ranges"

  publish_ranges: true

  publish_boundary: false

  boundary_topic: "/pathfinder/boundary"

  control_by_topic: false

  control_topic: "/pathfinder/control"
